Add print statement for the console debugging in run_tests.py
redhat-operator-ecosystem/operator-test-playbooks pull request #159
Opened 2021-06-23 19:04 UTC by samvarankashyap

$subject

2021-06-23 19:31 UTC, jsztuka approved these changes
lgtm

2021-06-24 11:36 UTC, lslebodn commented on Dockerfiles/midstream/run_tests.py
> +        print(result.stdout)
It should be logged mainly into output/validation-output.txt

2021-06-24 11:37 UTC, lslebodn commented on Dockerfiles/midstream/run_tests.py
> +        print(result)
We should not log internal data structures.

2021-06-24 11:37 UTC, lslebodn commented on Dockerfiles/midstream/run_tests.py
> +        print(result.stdout)
the same as above

2021-06-24 11:37 UTC, lslebodn requested changes
-1

2021-06-25 07:38 UTC, lslebodn commented
@samvarankashyap bump

2021-06-28 13:18 UTC, lslebodn commented
@samvarankashyap  bump ^^

2021-06-28 14:18 UTC, samvarankashyap commented
Yes.

2021-06-28 14:18 UTC, closed without merging