[CVP-1214] imporve logging of deploy operator olm playbooks
redhat-operator-ecosystem/operator-test-playbooks pull request #46
Opened 2020-08-20 13:34 UTC by samvarankashyap

The following improvement logs the error tasks to json file
such that it can be consumed by the pipeline. Further,
displays the failed task and its output.

2020-08-21 08:06 UTC, sonam1412 commented
/test CVP

2020-08-24 15:49 UTC, samvarankashyap commented
/test

2020-08-25 00:51 UTC, samvarankashyap commented
/test

2020-08-25 01:11 UTC, samvarankashyap commented
/test CVP

2020-08-25 12:59 UTC, samvarankashyap commented
@sonam1412 I wonder why tests arent getting triggered.

2020-08-25 15:33 UTC, samvarankashyap commented
/test CVP

2020-08-25 15:33 UTC, sonam1412 commented
> @sonam1412 I wonder why tests arent getting triggered.

can see PR#47 has test results on it, will try to re-trigger

2020-08-26 18:40 UTC, samvarankashyap commented
/test CVP

2020-08-27 10:47 UTC, dirgim requested changes

2020-08-27 10:47 UTC, dirgim commented on roles/deploy_olm_operator/tasks/main.yml
> +- name: "Set quay relase quay release"
Nit: typo 
```suggestion
- name: "Set quay release"
```

2020-08-27 10:47 UTC, dirgim commented on roles/deploy_olm_operator/tasks/main.yml
> +    - name: "Write parse_operator_metadata results to json file"
Nit: change task name to reflect the role
```suggestion
    - name: "Write deploy_olm_operator_results results to json file"
```

2020-08-27 10:47 UTC, dirgim commented on roles/deploy_olm_operator/tasks/main.yml
> +        deploy_olm_operator_results: {}
Don't we want to fill out the results json like in the [parsing role](https://github.com/redhat-operator-ecosystem/operator-test-playbooks/blob/master/roles/parse_operator_metadata/tasks/main.yml#L174)? e.g.
```suggestion
        deploy_olm_operator_results: {'result': 'pass', 'msg': ''}
```

2020-08-27 18:44 UTC, samvarankashyap commented
@dirgim PTAL

2020-08-27 18:58 UTC, samvarankashyap commented
/test CVP

2020-08-27 19:01 UTC, samvarankashyap commented
/test CVP

2020-08-27 19:31 UTC, samvarankashyap commented
/retest

2020-08-27 20:07 UTC, samvarankashyap commented
/test CVP

2020-08-27 20:29 UTC, samvarankashyap commented
/test CVP

2020-08-28 10:16 UTC, dirgim commented
/test CVP

2020-08-28 15:02 UTC, samvarankashyap commented
@sonam1412 @dirgim PTAL

2020-08-28 15:11 UTC, dirgim approved these changes
LGTM

2020-08-28 15:21 UTC, merged