Add documentation on operator test playbooks CI
redhat-operator-ecosystem/operator-test-playbooks pull request #75
Opened 2020-10-23 10:58 UTC by sonam1412

2020-11-03 09:27 UTC, jsztuka approved these changes
LGTM

2020-11-03 13:18 UTC, nmars commented on docs/operatorTestPlaybooksCI.md
> +Any activity (ex: adding comments) in the repository is therefore sent to github2fedmsg, which then rebroadcasts on the Fedora Messaging bus (fedmsg).
I suggest adding: `For more information on github2fedmsg and Fedora Messaging see https://github.com/fedora-infra/github2fedmsg.`

2020-11-03 18:30 UTC, 14rcole requested changes

2020-11-03 18:30 UTC, 14rcole commented on docs/operatorTestPlaybooksCI.md
> +This document is to describe about the working of the Upstream Operator Test Playbooks CI Pipeline.
Try this: `This document describes the Upstream Operator Test Playbooks CI Pipeline and how it works`

2020-11-03 18:30 UTC, 14rcole commented on docs/operatorTestPlaybooksCI.md
> +* The job is triggered by the Fedora Messaging messages which:
`...by a Fedora Messaging message which` or `by a message on the Fedora Messaging bus`

2020-11-03 18:30 UTC, 14rcole commented on docs/operatorTestPlaybooksCI.md
> +  * Indicate that a pull request was opened, re-opened, or synchronized (“synchronized” meaning that code changes were pushed to an already-opened pull request)
`Indicates`

2020-11-03 18:30 UTC, 14rcole commented on docs/operatorTestPlaybooksCI.md
> +  * Indicate a comment was added that contains the text `/retest` or `/test CVP`
`Indicates`

2020-11-03 18:30 UTC, 14rcole commented on docs/operatorTestPlaybooksCI.md
> +* The openshift project for the `test-operator-test-playbooks` is `cvp-ci-operatortestplaybooks`
You can remove the second `the`: `The openshift project for test-operator-test-playbooks...`

2020-11-03 18:30 UTC, 14rcole commented on docs/operatorTestPlaybooksCI.md
> +* The test-operator-test-playbooks job next configures it’s own [Team Jenkins server](https://jenkins-cvp-ci-operatortestplaybooks.cloud.paas.psi.redhat.com/) to run the testing pipelines.
Move the `next` to the beginning of the sentence

2020-11-04 12:03 UTC, lslebodn commented on docs/operatorTestPlaybooksCI.md
> +* The [test-operator-test-playbooks](https://jenkins-cvp-ci.cloud.paas.psi.redhat.com/job/test-operator-test-playbooks/) job runs on the CVP CI Jenkins server.
There should not be any internal links in upstream documentation.
It is unfair for the community.

2020-11-04 12:03 UTC, lslebodn commented on docs/operatorTestPlaybooksCI.md
> +* These are the same pipelines that run in production. The operators used for testing in these pipelines are the same used in [CVP-CI setup tests](https://gitlab.sat.engineering.redhat.com/cvp/pipeli
There should not be any internal links in upstream documentation.
It is unfair for the community.

2020-11-04 12:04 UTC, lslebodn commented on docs/operatorTestPlaybooksCI.md
> +  * [Example coldstorage URL](http://external-ci-coldstorage.datahub.redhat.com/cvp/cvp-redhat-operator-bundle-image-validation-test/e2e-test-operator-container-8.0-367/2b303e1a-a4a9-4815-b604-44d67c
There should not be any internal links in upstream documentation.
It is unfair for the community.

2020-11-09 11:31 UTC, dirgim approved these changes
LGTM

2020-11-09 12:42 UTC, merged